name: Build

on:
  push:
    branches:
    - master
    # For testing.
    - actions
    tags:
      - "v*.*"
    paths-ignore:
    - '*.{txt,md}'
    - 'Tools/**'
    - '.{editorconfig,gitattributes,gitignore}'
    - 'appveyor.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '*.{txt,md}'
    - 'Tools/**'
    - '.{editorconfig,gitattributes,gitignore}'
    - 'appveyor.yml'

env:
  BUILD_CONFIGURATION: Release

jobs:
  build-uwp:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build UWP
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        msbuild /m /p:TrackFileAccess=false /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=x64 /p:AppxPackageSigningEnabled=false UWP/PPSSPP_UWP.sln
        
        # Package the app into an AppX executable.
        C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\AppxPackaging\AppxPackage\MakeAppx.exe pack /l
        
        # Sign the AppX package.
        C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe sign /f ppsspp/UWP/PPSSPP_UWP_TemporaryKey.pfx PPSSPP_UWP.appx

    - name: Upload UWP build
      uses: actions/upload-artifact@v3
      with:
       name: UWP build
       path: UWP/
