name: Build

on:
  push:
    branches:
    - master
    # For testing.
    - actions
    tags:
      - "v*.*"
    paths-ignore:
    - '*.{txt,md}'
    - 'Tools/**'
    - '.{editorconfig,gitattributes,gitignore}'
    - 'appveyor.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '*.{txt,md}'
    - 'Tools/**'
    - '.{editorconfig,gitattributes,gitignore}'
    - 'appveyor.yml'

env:
  BUILD_CONFIGURATION: Release

jobs:
  build-windows:
    strategy:
      fail-fast: false

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@fail
      with:
        submodules: recursive

  build-uwp:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build UWP
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        msbuild /m /p:TrackFileAccess=false /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=x64 /p:AppxPackageSigningEnabled=false UWP/PPSSPP_UWP.sln
        
        # Package the app into an AppX or MSIX executable.
        if ($ENV:APPX_PACKAGE_FORMAT == "AppX") {
          makeappx.exe -p UWP/PPSSPP_UWP.appxmanifest -f Appx -r
        } else {
          makeappx.exe -p UWP/PPSSPP_UWP.appxmanifest -f MSIX -r
        }

    - name: Upload UWP build
      uses: actions/upload-artifact@v3
      with:
       name: UWP build
       path: UWP/
