name: Build

on:
  push:
    branches:
    - master
    # For testing.
    - actions
    tags:
      - "v*.*"
    paths-ignore:
    - '*.{txt,md}'
    - 'Tools/**'
    - '.{editorconfig,gitattributes,gitignore}'
    - 'appveyor.yml'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '*.{txt,md}'
    - 'Tools/**'
    - '.{editorconfig,gitattributes,gitignore}'
    - 'appveyor.yml'

env:
  APPX_PACKAGE_FORMAT: AppX

jobs:
  build-uwp:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
   
    - name: Install winget
      run: winget install winget
    
    - name: Install makeappx.exe
      run: winget install makeappx

    - name: Install signtool.exe
      run: winget install signtool

    - name: Build UWP
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        msbuild /m /p:Configuration=Release UWP/PPSSPP_UWP.sln
        
        # Package the app into an AppX executable.
        makeappx.exe -p UWP/PPSSPP_UWP.appxmanifest -f Appx -r

        # Sign the AppX package.
        signtool.exe sign /f ppsspp/UWP/PPSSPP_UWP_TemporaryKey.pfx UWP/PPSSPP_UWP.appx

    - name: Upload UWP build
      uses: actions/upload-artifact@v3
      with:
       name: UWP build
       path: UWP/
